### PR TITLE
Refactoring Repo

### PR DESCRIPTION
**Pull request by amanharitsh123**
Issue #2

### CODE REVIEW

**Comment by quozl** [comment]
@amanharitsh123, the upstream project rpi23-gen-image is copyright Jan Wagner <mail@jwagner.eu> and licensed as GPLv2+, and yet you are adding an Apache 2.0 license.  Is this legal?

* https://www.gnu.org/licenses/license-compatibility.en.html says

> One lax license, Apache 2.0, has patent clauses which are incompatible with GPL version 2

* https://www.apache.org/licenses/GPL-compatibility.html says

> The Free Software Foundation considers the Apache License, Version 2.0 to be a free software license, compatible with version 3 of the GPL. 

Perhaps you should first relicense as GPLv3+, then relicense as Apache 2.0.  While relicensing, be sure to change the license short text where it is found, such as in `rpi23-gen-image.sh`.

You can also contact the original author if you have any concerns about the license they chose for their work that you have copied.

**Comment by amanharitsh123** [comment]
@quozl  I dont have much idea about licensing .  Mentors have asked me to change the license to Apache V2 , well i dont know how to do that properly . Can you please help?

**Comment by quozl** [comment]
Mentors won't ask you to do something illegal as a test?  :grin:

If they asked you to do something, and you have feedback from someone else that what you've done may be illegal, or at least slightly wrong in exact steps, then ask them about it.  They might say "don't worry about him."

**Comment by llaske** [comment]
@quozl is right, you can't change the license from GPL2 to Apache 2.
My request was more about putting your own work into Apache 2 but if you mainly take your work from a work licensed with GPL2, let's stay on GPL2.

**Pull request merged**
